### ISSUE TITLE
AUC and Accuracy

### ISSUE THREAD

**Issue by 66Kevin** [jc-LeeHub/Recommend-System-tf2.0#1]
https://github.com/jc-LeeHub/Recommend-System-tf2.0/blob/921da9f9b5bbe92676156050d80b29ad2f23886d/FGCNN/train.py#L47
`print("AUC: ", accuracy_score(y_test, pre))` AUC不是这样计算的，这是计算accuracy。

**Comment by jc-LeeHub** [comment]
嗯嗯，谢谢指正
