### ISSUE TITLE
Wide&Deep 中wide侧和deep侧的输入问题

### ISSUE THREAD

**Issue by FlamingJay** [jc-LeeHub/Recommend-System-tf2.0#8]

**Comment by FlamingJay** [comment]
看论文以及一些博客，发现  deep侧的输入应该是[dense_raw_inputs, embedding]，是原特征中的连续值特征和稀疏特征embedding向量拼接在一块，而 wide侧的则是一些 特征工程特征，比如二阶的交叉特征等。
应该是这样的吧？

**Comment by jc-LeeHub** [comment]
> 看论文以及一些博客，发现 deep侧的输入应该是[dense_raw_inputs, embedding]，是原特征中的连续值特征和稀疏特征embedding向量拼接在一块，而 wide侧的则是一些 特征工程特征，比如二阶的交叉特征等。 应该是这样的吧？

是的
